# Generated by Django 3.2.4 on 2021-12-19 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import picklefield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='Company name')),
                ('next_sync_token', models.CharField(blank=True, default='', max_length=120, verbose_name='Sync Token')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Last Sync')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='Calendar name')),
                ('given_name', models.CharField(blank=True, default='', max_length=120, verbose_name='Hall name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('next_sync_token', models.CharField(blank=True, default='', max_length=120, verbose_name='Sync Token')),
                ('google_calendar_id', models.CharField(blank=True, default='', max_length=120, verbose_name='Google token')),
                ('disabled', models.BooleanField(default=True, verbose_name='Disabled for this company')),
                ('last_response', models.JSONField(blank=True, default=dict, null=True, verbose_name='Last Response')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='google_apps.company')),
            ],
            options={
                'verbose_name': 'Hall',
                'verbose_name_plural': 'Halls',
                'unique_together': {('company', 'google_calendar_id')},
            },
        ),
        migrations.CreateModel(
            name='GoogleCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('credentials', picklefield.fields.PickledObjectField(blank=True, editable=False, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google Credentials',
                'verbose_name_plural': 'Google Credentials',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='Event name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('next_sync_token', models.CharField(blank=True, default='', max_length=120, verbose_name='Sync Token')),
                ('google_id', models.CharField(blank=True, default='', max_length=120, verbose_name='Google token')),
                ('date_start', models.DateTimeField(blank=True, null=True, verbose_name='Event start')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Event end')),
                ('error', models.BooleanField(default=False, verbose_name='Date intersection error')),
                ('last_response', models.JSONField(blank=True, default=dict, null=True, verbose_name='Last Response')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='google_apps.company')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='google_apps.hall')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'unique_together': {('hall', 'google_id')},
            },
        ),
    ]
