# Generated by Django 3.2.4 on 2021-12-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_apps', '0002_alter_company_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hall',
            old_name='google_calendar_id',
            new_name='google_id',
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='company',
            name='google_id',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Google token'),
        ),
        migrations.AddField(
            model_name='company',
            name='last_response',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Last Response'),
        ),
        migrations.AddField(
            model_name='event',
            name='last_sync',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Sync'),
        ),
        migrations.AddField(
            model_name='hall',
            name='last_sync',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Sync'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='hall',
            unique_together={('company', 'google_id')},
        ),
    ]
