# Generated by Django 3.2.4 on 2021-12-20 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_apps', '0003_auto_20211220_2133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date_start'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
    ]
